### ISSUE TITLE
expath-pkg should make processor dependency explicit

### ISSUE THREAD

**Issue by duncdrum** [TEIC/xquery4roma#1]
I noticed that the app in docker is running in exist-db 3.3.0. Not sure if this is a hard dependency or not, but packages should declare their processor dependency in the `expath-pkg.xml` to prevent users from trying to run on incompatible versions.

If the app can run on any exist version declaring `semver-min="2.2.0"` will effectively do that, since older version can't process the instruction and will just ignore it. 

Otherwise adding the following to expath-pkg.xml would declare the 3.3.0 dependency in a way that modern exist can understand. 
```xml
<dependency processor="http://exist-db.org" semver-max="3.3.0"/>
```

[docs](http://exist-db.org/exist/apps/doc/repo.xml?field=all&id=D3.15#sect-expathpkg)

**Comment by peterstadler** [comment]
Thanks for the heads-up! 
I was in fact having some trouble with newer eXist versions (> 3.3.0) but now I tested again and all seems to work nicely. Hence I updated the Dockerfile along with your recommendation about expath-pkg.xml

Thanks again!
